Updated uses folder

diff --git a/.github/workflows/deploy-application-docs.yml b/.github/workflows/deploy-application-docs.yml
--- a/.github/workflows/deploy-application-docs.yml
+++ b/.github/workflows/deploy-application-docs.yml
@@ -19,7 +19,6 @@ on:
         description: 'Enable debug mode'
         required: false
         default: 'false'
-
   workflow_run:
     workflows: [ "🚀 Ship BaseShift Docs 📚" ]
     types:
@@ -48,7 +47,7 @@ jobs:
 
       # Use the custom action to handle submodules
       - name: Handle Git Submodules
-        uses: ./actions/handle-submodules
+        uses: ./.github/actions/handle-submodules
         with:
           branch: 'main'
 
@@ -59,12 +58,14 @@ jobs:
           git submodule status
           git submodule foreach 'echo $name && git log -1'
 
+      # Set up Python and install Poetry
       - name: Set up Python and Install Poetry 🛠️
         uses: ./actions/setup-python-poetry
         with:
           python-version: '3.x'
 
-      - name: List and build docs directories
+      # List and build docs directories
+      - name: List and Build Docs Directories
         id: build_docs
         run: |
           docs_dir=$(find applications -type d -name 'docs')
@@ -73,18 +74,36 @@ jobs:
             app_name=$(basename $(dirname "$dir"))
             echo "Processing $app_name in $dir"
             cd "$dir" || { echo "Failed to enter directory: $dir"; exit 1; }
+            
+            # Check if Sphinx is installed and build documentation
+            if ! command -v sphinx-build &> /dev/null; then
+              echo "Sphinx not found, installing..."
+              pip install sphinx
+            else
+              echo "Sphinx is already installed."
+            fi
+            
             make html
-            [ -f "build/html/index.html" ] || { echo "Error: index.html not found in $dir"; exit 1; }
+            
+            # Verify that the index.html file exists
+            if [ -f "build/html/index.html" ]; then
+              echo "index.html found in $dir"
+            else
+              echo "Error: index.html not found in $dir"
+              exit 1
+            fi
+            
+            # Upload the documentation to a subfolder corresponding to the application name
             mkdir -p $GITHUB_WORKSPACE/artifacts/$app_name
             cp -r build/html/* $GITHUB_WORKSPACE/artifacts/$app_name/
             cd ../../../
           done
         shell: bash
 
-      - name: List artifacts (for debugging) 🧐
+      - name: List Artifacts (for Debugging) 🧐
         run: ls -R artifacts/
 
-      - name: Upload all artifacts
+      - name: Upload All Artifacts
         if: success()
         uses: actions/upload-pages-artifact@v3
         with:
@@ -99,7 +118,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: build_and_deploy
     steps:
-      - name: Notify success or failure 🎉😞
+      - name: Notify Success or Failure 🎉😞
         run: |
           if [ "${{ needs.build_and_deploy.result }}" == "success" ]; then
             echo "🚀 Build and Deploy Sphinx Docs Success! 🎉"
